In [1]:
# X와 Y의 상관관계를 분석하는 기초적인 선형회귀 모델을 만들고 실행
# tensorflow를 이용해서 입력값(X)이 출력값(Y)으로 변환되는 함수
# X * w + b = Y에서 w와 b의 값을 찾는 것이 선형회귀 모델이다.

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

tf.enable_eager_execution()
tf.__version__

'1.15.0'

In [2]:
# X는 독립변수로 입력값
X = [1, 2, 3]
# Y는 종속변수로 출력값
Y = [3, 5, 7]

In [3]:
# 난수 1개를 w와 b에 대입
# tf.random_normal은 난수를 생성
# tf.random_normal(생성할 난수의 형식으로 1개의 데이터가 저장된 배열로 설정,
#                   생성할 난수의 평균, 생성할 난수의 표준편차)

w = tf.Variable(tf.random_normal([1], 0., 1.))
b = tf.Variable(tf.random_normal([1], 0., 1.))

In [5]:
# w에 대입된 난수 출력
print(w.numpy()[0])

0.9505727


In [6]:
# b에 대입된 난수 출력
print(b.numpy()[0])

-0.108677514


In [7]:
# learning_rate 설정
learning_rate = 0.1

In [8]:
# 300번 반복해서 w, b를 업데이트
for i in range(300):
    # Gradient descent를 실행해서 w와 b를 업데이트 할 객체 tape를 생성
    with tf.GradientTape() as tape:
        # X * w + b를 계산해서 예측값을 hypothesis에 대입
        hypothesis = X * w + b
        print("hypothesis: ", hypothesis)
        # tf.square(값): 값의 제곱을 계산해서 리턴하는 함수
        # tf.reduce_mean(): 평균을 계산하는 함수
        # 예측값 hypothesis에서 실제값 Y의 차(잔차)의 제곱의 평균을 cost에 대입
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
        print("cost: ", cost)
    # cost, w, b를 이용하여 w_grad, b_grad 계산해서 리턴
    w_grad, b_grad = tape.gradient(cost, [w, b])
    print("w_grad: ", w_grad, "b_grad: ", b_grad)
    # w.assign_sub(값1): w을 값1만큼 감소시키는 함수
    # w를 w_grad * learning_rate만큼 감소시킴
    w.assign_sub(w_grad * learning_rate)
    # b.assign_sub(값1): b을 값1만큼 감소시키는 함수
    # b를 b_grad * learning_rate만큼 감소시킴
    b.assign_sub(b_grad * learning_rate)

hypothesis:  tf.Tensor([0.8418952 1.792468  2.7430406], shape=(3,), dtype=float32)
cost:  tf.Tensor(11.022461, shape=(), dtype=float32)
w_grad:  tf.Tensor([-14.229366], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-6.415065], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9063385 5.2798476 7.653357 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.17132086, shape=(), dtype=float32)
w_grad:  tf.Tensor([1.6174033], shape=(1,), dtype=float32) b_grad:  tf.Tensor([0.5596954], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.6886287 4.900398  7.112167 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.039818037, shape=(), dtype=float32)
w_grad:  tf.Tensor([-0.11605009], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.19920444], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.720154 4.943528 7.166902], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.036453042, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.07194439], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.11294381], s

w_grad:  tf.Tensor([0.01150624], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.02615468], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9405258 4.987237  7.0339484], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.0016175248, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.01122999], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.02552589], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9419553 4.9875436 7.0331316], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.0015406831, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.01095819], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.02491299], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9433508 4.9878435 7.0323358], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.0014675047, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.01069673], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.02431329], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9447124 4.9881353 7.031558 ], shape=(3,), dtype=float32)
cost:  tf.Tensor

hypothesis:  tf.Tensor([2.979613  4.995625  7.0116367], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.00019006037, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00384887], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00875012], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9801033 4.9957304 7.011358 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.00018103642, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00375827], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00853904], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9805813 4.995833  7.0110846], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.0001724395, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00366719], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00833416], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.981048  4.9959326 7.010817 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(0.00016424224, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00357628], shape=(1,), dtype=float32) b_grad:  tf.Tensor

w_grad:  tf.Tensor([0.00125821], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00285625], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9935036 4.9986057 7.003708 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(1.9298668e-05, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00122579], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00278854], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9936597 4.9986396 7.003619 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(1.8382754e-05, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00119766], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00272099], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.993812 4.998672 7.003532], shape=(3,), dtype=float32)
cost:  tf.Tensor(1.750947e-05, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00116793], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00265598], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9939609 4.998704  7.003447 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(

w_grad:  tf.Tensor([0.00043297], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00097847], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.997773  4.9995217 7.0012703], shape=(3,), dtype=float32)
cost:  tf.Tensor(2.2674064e-06, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00041819], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00095669], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9978268 4.999534  7.001241 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(2.1601215e-06, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00041246], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.0009319], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9978788 4.9995446 7.00121  ], shape=(3,), dtype=float32)
cost:  tf.Tensor(2.0571724e-06, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00039911], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00091092], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.99793  4.999556 7.001182], shape=(3,), dtype=float32)
cost:  tf.Tensor(

cost:  tf.Tensor(3.9313431e-07, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00017532], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00039784], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.999095  4.9998055 7.0005164], shape=(3,), dtype=float32)
cost:  tf.Tensor(3.7454183e-07, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00017007], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00038878], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.999117  4.9998107 7.0005045], shape=(3,), dtype=float32)
cost:  tf.Tensor(3.5673997e-07, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00016785], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00037861], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9991379 4.999815  7.000492 ], shape=(3,), dtype=float32)
cost:  tf.Tensor(3.398806e-07, shape=(), dtype=float32)
w_grad:  tf.Tensor([0.00016276], shape=(1,), dtype=float32) b_grad:  tf.Tensor([-0.00037003], shape=(1,), dtype=float32)
hypothesis:  tf.Tensor([2.9991589 4.9998