In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [3]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = data.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
y = y.reshape(-1, 1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
X_train

array([[6. , 3.4, 4.5, 1.6],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.5, 3.2, 5.1, 2. ],
       [5. , 3.4, 1.6, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [6.6, 2.9, 4.6, 1.3],
       [5.8, 2.7, 3.9, 1.2],
       [7.2, 3. , 5.8, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.5, 2.8, 4.6, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [6.2, 2.2, 4.5, 1.5],
       [4.9, 3.6, 1.4, 0.1],
       [6.5, 3. , 5.8, 2.2],
       [5.2, 3.5, 1.5, 0.2],
       [6. , 2.2, 5. , 1.5],
       [5.7, 3. , 4.2, 1.2],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.8, 4.5, 1.3],
       [5.1, 3.8, 1.6, 0.2],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [6.9, 3.2, 5.7, 2.3],
       [4.9, 2.5, 4.5, 1.7],
       [4.7, 3.2, 1.6, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5.1, 3.5, 1.4, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [5.4, 3

In [12]:
X_test

array([[6.4, 3.2, 5.3, 2.3],
       [5.5, 3.5, 1.3, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [5.2, 3.4, 1.4, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3. , 1.4, 0.3],
       [7. , 3.2, 4.7, 1.4],
       [4.4, 3. , 1.3, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [6.9, 3.1, 5.1, 2.3],
       [4.6, 3.4, 1.4, 0.3],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [4.9, 3. , 1.4, 0.2],
       [6.4, 2.9, 4.3, 1.3],
       [4.8, 3. , 1.4, 0.1],
       [5. , 3. , 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5.6, 3. , 4.1, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5.6, 2.5, 3.9, 1.1],
       [5.1, 3.8, 1.9, 0.4],
       [6. , 2.2, 4. , 1. ]])

In [13]:
y_train

array([[1],
       [2],
       [2],
       [0],
       [2],
       [0],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [2],
       [1],
       [0],
       [1],
       [0],
       [2],
       [2],
       [0],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [0],
       [1],
       [0],
       [0],
       [2],
       [0],
       [1],
       [2],
       [0],
       [1],
       [1],
       [0],
       [0],
       [2],
       [0],
       [2],
       [0],
       [1],
    

In [14]:
y_test

array([[2],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [2],
       [2],
       [0],
       [0],
       [1],
       [2],
       [2],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [0],
       [1]])

In [15]:
# X에서 평균을 빼고 표준편차로 나눠서 평균 -> 0, 표준편차 -> 1로 변환할 객체 생성
# scaler.fit(--): --의 평균, 표준편차를 계산
# scaler.transform(--): --에서 평균을 뺴고 표준편차로 나눈다
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
X_train = scaler.transform(X_train)
X_train

array([[ 0.17087531,  0.73999917,  0.39567465,  0.51158645],
       [-0.20194355, -1.23333196,  0.68308965,  1.05128206],
       [-0.0776706 , -0.57555491,  0.74057265,  1.59097766],
       [-1.69321899, -1.67184999, -1.44378135, -1.24242425],
       [ 0.79224008,  0.30148115,  0.74057265,  1.05128206],
       [-1.07185422,  0.73999917, -1.27133235, -1.10750035],
       [ 0.41942122, -0.3562959 ,  0.28070865,  0.10681475],
       [ 0.91651303, -0.3562959 ,  0.45315765,  0.10681475],
       [-0.0776706 , -0.79481393,  0.05077665, -0.02810915],
       [ 1.66215075, -0.13703688,  1.14295365,  0.51158645],
       [ 0.54369417,  0.52074016,  1.25791965,  1.72590156],
       [ 0.66796713,  0.08222213,  0.97050465,  0.78143425],
       [ 0.79224008, -0.57555491,  0.45315765,  0.37666255],
       [ 0.17087531, -0.3562959 ,  0.39567465,  0.37666255],
       [-0.20194355,  2.93258932, -1.32881535, -1.10750035],
       [-0.94758127,  0.52074016, -1.21384935, -0.97257645],
       [ 0.41942122, -1.

In [17]:
from sklearn.preprocessing import OneHotEncoder
# 데이터를 one hot 인코딩 할 객체
enc = OneHotEncoder()
# y가 몇가지 종류인지 파악
enc.fit(y)

C:\ai\python\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [18]:
# toarray(): one hot encoding 한 데이터를 numpy 배열로 변환
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1

In [19]:
y_train_onehot = np.array(y_train_onehot, dtype = "float32")
y_train_onehot

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1

In [20]:
y_test_onehot = enc.transform(y_test).toarray()
y_test_onehot

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [21]:
y_test_onehot = np.array(y_test_onehot, dtype="float32")
y_test_onehot

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [22]:
model = Sequential()
model.add(Dense(16, input_dim=4, activation="sigmoid"))

In [25]:
model.add(Dense(3, activation = "softmax"))

In [26]:
# param counting 하는 방법 궁금!!
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(loss="categorical_crossentropy", optimizer=Adam(lr=0.1),metrics=['acc'])

In [29]:
model.fit(X_train, y_train_onehot, epochs=1000)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/1000





120/120 [==============================] - 0s 3ms/step - loss: 0.9093 - acc: 0.6250
Epoch 2/1000
120/120 [==============================] - 0s 100us/step - loss: 0.4407 - acc: 0.8333
Epoch 3/1000
120/120 [==============================] - 0s 91us/step - loss: 0.3537 - acc: 0.8583
Epoch 4/1000
120/120 [==============================] - 0s 58us/step - loss: 0.2732 - acc: 0.8667
Epoch 5/1000
120/120 [==============================] - 0s 83us/step - loss: 0.2286 - acc: 0.9083
Epoch 6/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1847 - acc: 0.9500
Epoch 7/1000
120/120 [==============================] - 0s 83us/step - loss: 0.1419 - acc: 0.9583
Epoch 8/1000
120/120 [==============================] - 0s 100us/step - loss: 0.1056 - acc: 0.9667
Epoch 9/1000
120/120 [==============================] - 0s 108us/step - loss: 0.1034 - acc: 0.9583
Epoch 10/1000


120/120 [==============================] - 0s 125us/step - loss: 0.0476 - acc: 0.9750
Epoch 65/1000
120/120 [==============================] - 0s 108us/step - loss: 0.0483 - acc: 0.9833
Epoch 66/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0511 - acc: 0.9917
Epoch 67/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0484 - acc: 0.9833
Epoch 68/1000
120/120 [==============================] - 0s 116us/step - loss: 0.0469 - acc: 0.9833
Epoch 69/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0574 - acc: 0.9667
Epoch 70/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0413 - acc: 0.9833
Epoch 71/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0688 - acc: 0.9750
Epoch 72/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0432 - acc: 0.9833
Epoch 73/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0696 - acc: 0.9667
Epoch 74/1000
120/12

120/120 [==============================] - 0s 100us/step - loss: 0.0645 - acc: 0.9833
Epoch 146/1000
120/120 [==============================] - 0s 125us/step - loss: 0.0406 - acc: 0.9833
Epoch 147/1000
120/120 [==============================] - 0s 108us/step - loss: 0.0500 - acc: 0.9833
Epoch 148/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0361 - acc: 0.9833
Epoch 149/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0428 - acc: 0.9833
Epoch 150/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0443 - acc: 0.9833
Epoch 151/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0382 - acc: 0.9833
Epoch 152/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0405 - acc: 0.9833
Epoch 153/1000
120/120 [==============================] - 0s 116us/step - loss: 0.0449 - acc: 0.9833
Epoch 154/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0490 - acc: 0.9833
Epoch 155/

120/120 [==============================] - 0s 91us/step - loss: 0.0330 - acc: 0.9917
Epoch 227/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0321 - acc: 0.9833
Epoch 228/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0314 - acc: 0.9833
Epoch 229/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0352 - acc: 0.9917
Epoch 230/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0380 - acc: 0.9833
Epoch 231/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0352 - acc: 0.9833
Epoch 232/1000
120/120 [==============================] - 0s 116us/step - loss: 0.0312 - acc: 0.9917
Epoch 233/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0303 - acc: 0.9917
Epoch 234/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0315 - acc: 0.9833
Epoch 235/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0313 - acc: 0.9833
Epoch 236/10

120/120 [==============================] - 0s 66us/step - loss: 0.0081 - acc: 1.0000
Epoch 308/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0078 - acc: 1.0000
Epoch 309/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0079 - acc: 1.0000
Epoch 310/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0073 - acc: 1.0000
Epoch 311/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0085 - acc: 1.0000
Epoch 312/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0068 - acc: 1.0000
Epoch 313/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0071 - acc: 1.0000
Epoch 314/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0073 - acc: 1.0000
Epoch 315/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0064 - acc: 1.0000
Epoch 316/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0066 - acc: 1.0000
Epoch 317/1000


120/120 [==============================] - 0s 75us/step - loss: 0.0021 - acc: 1.0000
Epoch 389/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0020 - acc: 1.0000
Epoch 390/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0020 - acc: 1.0000
Epoch 391/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0020 - acc: 1.0000
Epoch 392/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0020 - acc: 1.0000
Epoch 393/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0019 - acc: 1.0000
Epoch 394/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0019 - acc: 1.0000
Epoch 395/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0019 - acc: 1.0000
Epoch 396/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0019 - acc: 1.0000
Epoch 397/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0019 - acc: 1.0000
Epoch 398/1000

120/120 [==============================] - 0s 83us/step - loss: 0.0010 - acc: 1.0000
Epoch 470/1000
120/120 [==============================] - 0s 100us/step - loss: 9.9882e-04 - acc: 1.0000
Epoch 471/1000
120/120 [==============================] - 0s 75us/step - loss: 9.9710e-04 - acc: 1.0000
Epoch 472/1000
120/120 [==============================] - 0s 91us/step - loss: 9.8717e-04 - acc: 1.0000
Epoch 473/1000
120/120 [==============================] - 0s 133us/step - loss: 9.9829e-04 - acc: 1.0000
Epoch 474/1000
120/120 [==============================] - 0s 83us/step - loss: 9.6728e-04 - acc: 1.0000
Epoch 475/1000
120/120 [==============================] - 0s 100us/step - loss: 9.5992e-04 - acc: 1.0000
Epoch 476/1000
120/120 [==============================] - 0s 100us/step - loss: 9.7669e-04 - acc: 1.0000
Epoch 477/1000
120/120 [==============================] - 0s 91us/step - loss: 9.5181e-04 - acc: 1.0000
Epoch 478/1000
120/120 [==============================] - 0s 91us/step - loss: 

120/120 [==============================] - 0s 66us/step - loss: 6.1298e-04 - acc: 1.0000
Epoch 548/1000
120/120 [==============================] - 0s 66us/step - loss: 6.1232e-04 - acc: 1.0000
Epoch 549/1000
120/120 [==============================] - 0s 91us/step - loss: 6.1104e-04 - acc: 1.0000
Epoch 550/1000
120/120 [==============================] - 0s 75us/step - loss: 6.0549e-04 - acc: 1.0000
Epoch 551/1000
120/120 [==============================] - 0s 75us/step - loss: 6.1981e-04 - acc: 1.0000
Epoch 552/1000
120/120 [==============================] - 0s 91us/step - loss: 6.0033e-04 - acc: 1.0000
Epoch 553/1000
120/120 [==============================] - 0s 83us/step - loss: 6.0173e-04 - acc: 1.0000
Epoch 554/1000
120/120 [==============================] - 0s 91us/step - loss: 5.9133e-04 - acc: 1.0000
Epoch 555/1000
120/120 [==============================] - 0s 75us/step - loss: 6.0039e-04 - acc: 1.0000
Epoch 556/1000
120/120 [==============================] - 0s 83us/step - loss: 

120/120 [==============================] - 0s 91us/step - loss: 4.1691e-04 - acc: 1.0000
Epoch 626/1000
120/120 [==============================] - 0s 83us/step - loss: 4.2329e-04 - acc: 1.0000
Epoch 627/1000
120/120 [==============================] - 0s 66us/step - loss: 4.0847e-04 - acc: 1.0000
Epoch 628/1000
120/120 [==============================] - 0s 100us/step - loss: 4.1313e-04 - acc: 1.0000
Epoch 629/1000
120/120 [==============================] - 0s 100us/step - loss: 4.1492e-04 - acc: 1.0000
Epoch 630/1000
120/120 [==============================] - 0s 91us/step - loss: 4.1055e-04 - acc: 1.0000
Epoch 631/1000
120/120 [==============================] - 0s 66us/step - loss: 4.0496e-04 - acc: 1.0000
Epoch 632/1000
120/120 [==============================] - 0s 66us/step - loss: 4.0052e-04 - acc: 1.0000
Epoch 633/1000
120/120 [==============================] - 0s 83us/step - loss: 4.0222e-04 - acc: 1.0000
Epoch 634/1000
120/120 [==============================] - 0s 91us/step - loss

120/120 [==============================] - 0s 83us/step - loss: 2.9659e-04 - acc: 1.0000
Epoch 704/1000
120/120 [==============================] - 0s 66us/step - loss: 2.9246e-04 - acc: 1.0000
Epoch 705/1000
120/120 [==============================] - 0s 58us/step - loss: 2.9443e-04 - acc: 1.0000
Epoch 706/1000
120/120 [==============================] - 0s 66us/step - loss: 2.9316e-04 - acc: 1.0000
Epoch 707/1000
120/120 [==============================] - 0s 83us/step - loss: 2.9804e-04 - acc: 1.0000
Epoch 708/1000
120/120 [==============================] - 0s 91us/step - loss: 2.9379e-04 - acc: 1.0000
Epoch 709/1000
120/120 [==============================] - 0s 83us/step - loss: 2.8945e-04 - acc: 1.0000
Epoch 710/1000
120/120 [==============================] - 0s 125us/step - loss: 2.8651e-04 - acc: 1.0000
Epoch 711/1000
120/120 [==============================] - 0s 83us/step - loss: 2.8495e-04 - acc: 1.0000
Epoch 712/1000
120/120 [==============================] - 0s 75us/step - loss:

120/120 [==============================] - 0s 91us/step - loss: 2.1895e-04 - acc: 1.0000
Epoch 782/1000
120/120 [==============================] - 0s 91us/step - loss: 2.1854e-04 - acc: 1.0000
Epoch 783/1000
120/120 [==============================] - ETA: 0s - loss: 2.9433e-04 - acc: 1.000 - 0s 66us/step - loss: 2.2322e-04 - acc: 1.0000
Epoch 784/1000
120/120 [==============================] - 0s 66us/step - loss: 2.1790e-04 - acc: 1.0000
Epoch 785/1000
120/120 [==============================] - 0s 91us/step - loss: 2.1755e-04 - acc: 1.0000
Epoch 786/1000
120/120 [==============================] - 0s 83us/step - loss: 2.1515e-04 - acc: 1.0000
Epoch 787/1000
120/120 [==============================] - 0s 75us/step - loss: 2.1585e-04 - acc: 1.0000
Epoch 788/1000
120/120 [==============================] - 0s 66us/step - loss: 2.1330e-04 - acc: 1.0000
Epoch 789/1000
120/120 [==============================] - 0s 83us/step - loss: 2.1433e-04 - acc: 1.0000
Epoch 790/1000
120/120 [=============

120/120 [==============================] - 0s 91us/step - loss: 1.6670e-04 - acc: 1.0000
Epoch 860/1000
120/120 [==============================] - 0s 91us/step - loss: 1.6668e-04 - acc: 1.0000
Epoch 861/1000
120/120 [==============================] - 0s 67us/step - loss: 1.6568e-04 - acc: 1.0000
Epoch 862/1000
120/120 [==============================] - 0s 108us/step - loss: 1.6456e-04 - acc: 1.0000
Epoch 863/1000
120/120 [==============================] - 0s 83us/step - loss: 1.6497e-04 - acc: 1.0000
Epoch 864/1000
120/120 [==============================] - 0s 66us/step - loss: 1.6478e-04 - acc: 1.0000
Epoch 865/1000
120/120 [==============================] - 0s 75us/step - loss: 1.6314e-04 - acc: 1.0000
Epoch 866/1000
120/120 [==============================] - 0s 75us/step - loss: 1.6360e-04 - acc: 1.0000
Epoch 867/1000
120/120 [==============================] - 0s 108us/step - loss: 1.6391e-04 - acc: 1.0000
Epoch 868/1000
120/120 [==============================] - 0s 75us/step - loss

120/120 [==============================] - 0s 75us/step - loss: 1.2907e-04 - acc: 1.0000
Epoch 938/1000
120/120 [==============================] - 0s 58us/step - loss: 1.3078e-04 - acc: 1.0000
Epoch 939/1000
120/120 [==============================] - 0s 100us/step - loss: 1.2851e-04 - acc: 1.0000
Epoch 940/1000
120/120 [==============================] - 0s 66us/step - loss: 1.2862e-04 - acc: 1.0000
Epoch 941/1000
120/120 [==============================] - 0s 133us/step - loss: 1.2887e-04 - acc: 1.0000
Epoch 942/1000
120/120 [==============================] - 0s 100us/step - loss: 1.2748e-04 - acc: 1.0000
Epoch 943/1000
120/120 [==============================] - 0s 91us/step - loss: 1.2766e-04 - acc: 1.0000
Epoch 944/1000
120/120 [==============================] - 0s 83us/step - loss: 1.2719e-04 - acc: 1.0000
Epoch 945/1000
120/120 [==============================] - 0s 116us/step - loss: 1.2797e-04 - acc: 1.0000
Epoch 946/1000
120/120 [==============================] - 0s 100us/step - l

In [30]:
X_test = scaler.transform(X_test)
X_test

array([[ 0.66796713,  0.30148115,  0.85553865,  1.45605376],
       [-0.45048946,  0.95925819, -1.44378135, -1.37734815],
       [ 2.28351552, -1.01407294,  1.77526666,  1.45605376],
       [-0.82330832,  0.73999917, -1.38629835, -1.37734815],
       [-1.56894604,  0.30148115, -1.38629835, -1.37734815],
       [-0.3262165 , -0.13703688,  0.39567465,  0.37666255],
       [-1.32040013, -0.13703688, -1.38629835, -1.24242425],
       [ 1.41360485,  0.30148115,  0.51064065,  0.24173865],
       [-1.81749195, -0.13703688, -1.44378135, -1.37734815],
       [ 1.28933189,  0.08222213,  0.91302165,  1.18620596],
       [ 1.28933189,  0.08222213,  0.74057265,  1.45605376],
       [-1.56894604,  0.73999917, -1.38629835, -1.24242425],
       [-1.19612718,  0.08222213, -1.32881535, -1.51227205],
       [-0.20194355, -0.3562959 ,  0.22322565,  0.10681475],
       [ 0.41942122, -0.57555491,  0.56812365,  0.78143425],
       [ 0.04660236, -0.13703688,  0.74057265,  0.78143425],
       [-1.19612718, -0.

In [31]:
predict = model.predict(X_test)
predict

array([[3.1115984e-13, 6.1161671e-08, 9.9999988e-01],
       [9.9999142e-01, 8.5450583e-06, 1.8819903e-32],
       [6.7108041e-19, 2.5488054e-12, 1.0000000e+00],
       [9.9999142e-01, 8.5602614e-06, 1.9152769e-32],
       [9.9999142e-01, 8.5780939e-06, 2.3488317e-32],
       [2.4137273e-07, 9.9999976e-01, 3.7495706e-08],
       [9.9999046e-01, 9.5533333e-06, 3.2209694e-32],
       [4.6614987e-06, 9.9999535e-01, 6.1662457e-09],
       [9.9998963e-01, 1.0330119e-05, 5.7076457e-31],
       [1.1531730e-11, 1.7534869e-06, 9.9999821e-01],
       [2.5453513e-09, 1.6926156e-04, 9.9983072e-01],
       [9.9999785e-01, 2.1592618e-06, 4.3013962e-31],
       [9.9999118e-01, 8.8413117e-06, 2.0610248e-32],
       [1.4262367e-08, 1.0000000e+00, 2.4942346e-16],
       [2.0307067e-09, 1.0868566e-02, 9.8913145e-01],
       [1.8321043e-10, 7.4585271e-04, 9.9925417e-01],
       [9.9999082e-01, 9.1694092e-06, 2.4385242e-32],
       [2.1498797e-06, 9.9999785e-01, 2.4868085e-09],
       [9.9999106e-01, 8.949

In [32]:
# np.argmax(predict, 1): predict 최대값의 인덱스를 리턴
#                    1: 각 줄에서 최대값의 인덱스를 리턴
predict01 = np.argmax(predict, 1)
predict01

array([2, 0, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 2, 1, 1, 1, 0, 1], dtype=int64)

In [33]:
target = np.argmax(y_test_onehot, 1)
target

array([2, 0, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 1,
       2, 2, 2, 1, 1, 1, 0, 1], dtype=int64)

In [34]:
predict02 = (predict01 == target)
predict02

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [35]:
np.sum(predict02)

29

In [36]:
# 정확도를 계산
# len(predict02): predict02의 줄의 수를 리턴
acc = np.sum(predict02) / len(predict02)
acc

0.9666666666666667