In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [3]:
data = datasets.load_breast_cancer()
data
# dictionary 형태로 되어있다
# data = 독립변수
# target = 종속변수

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
# 유방암 판단의 독립변수를 읽어서 X에 저장
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
# X의 데이터 타입을 float32로 변환
# tensorflow에서 연산 가능
X = np.array(X, dtype = "float32")
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [6]:
# 유방암 데이터의 종속변수
# 유방암이 악성이면 0, 양성이면 1
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
# y의 데이터 타입을 float32로 변환
# tensorflow에서 연산 가능
y = np.array(y, dtype = "float32")
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [8]:
# y.reshape(): 1차원 배열을 2차원 배열로 변환
# y.reshape(1, -1): [[1, 0, 1, 0 ...]]: 행 형태의 2차원 배열로 변환
# y.reshape(-1, 1): 

# 줄은 생략하고 1칸 하겠다 / (줄, 칸)
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [13]:
train_test_split(X, y, test_size = 0.2)

[array([[1.221e+01, 1.409e+01, 7.878e+01, ..., 9.140e-02, 2.677e-01,
         8.824e-02],
        [1.126e+01, 1.996e+01, 7.372e+01, ..., 9.314e-02, 2.955e-01,
         7.009e-02],
        [1.459e+01, 2.268e+01, 9.639e+01, ..., 1.105e-01, 2.258e-01,
         8.004e-02],
        ...,
        [1.918e+01, 2.249e+01, 1.275e+02, ..., 1.708e-01, 3.193e-01,
         9.221e-02],
        [1.096e+01, 1.762e+01, 7.079e+01, ..., 9.861e-02, 2.289e-01,
         8.278e-02],
        [1.500e+01, 1.551e+01, 9.745e+01, ..., 1.379e-01, 2.954e-01,
         8.362e-02]], dtype=float32),
 array([[9.876e+00, 1.940e+01, 6.395e+01, ..., 9.749e-02, 2.622e-01,
         8.490e-02],
        [2.051e+01, 2.781e+01, 1.344e+02, ..., 1.563e-01, 2.437e-01,
         8.328e-02],
        [9.738e+00, 1.197e+01, 6.124e+01, ..., 0.000e+00, 3.105e-01,
         8.151e-02],
        ...,
        [6.981e+00, 1.343e+01, 4.379e+01, ..., 0.000e+00, 2.932e-01,
         9.382e-02],
        [1.808e+01, 2.184e+01, 1.174e+02, ..., 9.181e-02,

In [10]:
# X, y를 8:2로 나눠서 80%는 X_train, y_train, 20%는 X_test, y_test에 대입
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
# 독립변수의 80% 저장
# shape (줄, 칸) 확인 가능
X_train.shape

(455, 30)

In [15]:
# 독립변수의 20% 저장
# shape (줄, 칸) 확인 가능
X_test.shape

(114, 30)

In [16]:
# 종속 변수의 80% 저장 (0: 악성 종양, 1: 양성 종양)
y_train.shape

(455, 1)

In [17]:
# 종속 변수의 20% 저장 (0: 악성 종양, 1: 양성 종양)
y_test.shape

(114, 1)

In [18]:
X_train

array([[1.458e+01, 2.153e+01, 9.741e+01, ..., 2.701e-01, 4.264e-01,
        1.275e-01],
       [2.044e+01, 2.178e+01, 1.338e+02, ..., 1.765e-01, 2.609e-01,
        6.735e-02],
       [2.227e+01, 1.967e+01, 1.528e+02, ..., 2.910e-01, 4.055e-01,
        9.789e-02],
       ...,
       [9.676e+00, 1.314e+01, 6.412e+01, ..., 1.075e-01, 2.848e-01,
        1.364e-01],
       [1.321e+01, 2.806e+01, 8.488e+01, ..., 7.958e-02, 2.473e-01,
        6.443e-02],
       [1.944e+01, 1.882e+01, 1.281e+02, ..., 2.060e-01, 3.266e-01,
        9.009e-02]], dtype=float32)

In [20]:
from sklearn.preprocessing import StandardScaler
# X에서 평균을 뺴고 표준편차로 나눠서 평균 -> 0, 표준편차 -> 1로 변환할 객체
scaler = StandardScaler()
# scaler.fit(X_train): X_train의 평균, 표준편차를 계산
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [21]:
# scaler.transform(X_train): X_train에서 평균을 빼고 표준편차로 나눠서 X_train에 대입
X_train = scaler.transform(X_train)
X_train

array([[ 0.05227502,  0.49119914,  0.145944  , ...,  2.2850492 ,
         2.14064   ,  2.3757257 ],
       [ 1.6877182 ,  0.54962695,  1.6162289 , ...,  0.885006  ,
        -0.46526524, -0.9104318 ],
       [ 2.198445  ,  0.0564963 ,  2.383896  , ...,  2.5976658 ,
         1.8115557 ,  0.7580511 ],
       ...,
       [-1.316362  , -1.4696375 , -1.19909   , ..., -0.14707682,
        -0.08894418,  2.8619568 ],
       [-0.33007252,  2.0173326 , -0.3603126 , ..., -0.56469643,
        -0.6794059 , -1.0699594 ],
       [ 1.4086323 , -0.14215827,  1.3859289 , ...,  1.3262589 ,
         0.5692238 ,  0.33191603]], dtype=float32)

In [22]:
# h를 0 ~ 1 사이 범위로 변경하는 활성함수 선언
def sigmoid(h):
    return 1 / (1 + np.exp(-h))

In [23]:
# tf.contrib.layers.xavier_initializer(): w와 b를 초기화 시키는 객체를 생성
initializer = tf.contrib.layers.xavier_initializer()

# tf.Variable(initializer([30, 1])): 30줄 1칸의 w를 생성해서 return
w = tf.Variable(initializer([30, 1]))
w

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.22706492],
       [ 0.37751597],
       [-0.2553195 ],
       [-0.17585218],
       [ 0.00856584],
       [ 0.3797906 ],
       [-0.23636532],
       [-0.17408079],
       [-0.42986873],
       [ 0.2516111 ],
       [ 0.20445079],
       [-0.27776852],
       [-0.00923023],
       [-0.3319743 ],
       [-0.28946388],
       [-0.39865887],
       [-0.22734918],
       [ 0.2800272 ],
       [ 0.38392413],
       [-0.16099134],
       [-0.30810887],
       [-0.2044463 ],
       [ 0.1261589 ],
       [-0.2847088 ],
       [ 0.16470289],
       [-0.27035666],
       [ 0.3009097 ],
       [-0.3440693 ],
       [-0.35064685],
       [ 0.23960745]], dtype=float32)>

In [24]:
# tf.Variable(initializer([1])): 1줄 1칸의 b를 생성해서 return
b = tf.Variable(initializer([1]))
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.12596595], dtype=float32)>

In [25]:
# tf.matmul(X_train, w) + b: X_train에 w를 곱하고 b를 더해서 선형회귀를 계산
tf.matmul(X_train, w) + b

<tf.Tensor: id=35, shape=(455, 1), dtype=float32, numpy=
array([[-1.1516229 ],
       [-1.558675  ],
       [-6.1379523 ],
       [-0.7948189 ],
       [ 1.3451754 ],
       [ 0.30161017],
       [-0.69141924],
       [ 1.4301574 ],
       [ 1.8455212 ],
       [ 0.5249865 ],
       [ 1.7016631 ],
       [ 1.6493794 ],
       [ 1.1861875 ],
       [ 1.8019431 ],
       [ 0.66740394],
       [-0.02985093],
       [ 1.3603002 ],
       [ 1.9128618 ],
       [-1.0148946 ],
       [-3.3890047 ],
       [ 1.461572  ],
       [ 0.4711893 ],
       [ 0.9870093 ],
       [-1.8454171 ],
       [-3.977491  ],
       [ 1.0727937 ],
       [-2.6542897 ],
       [ 1.9195986 ],
       [ 0.9762855 ],
       [-1.6301858 ],
       [-0.97594106],
       [ 1.6258518 ],
       [ 0.29820508],
       [-0.3783031 ],
       [ 0.22741103],
       [ 0.8193452 ],
       [ 0.48138672],
       [-2.3726306 ],
       [-0.15861455],
       [ 1.8792667 ],
       [ 1.2963068 ],
       [-5.723523  ],
       [-8.938606  

In [26]:
# tf.matmul(X_train, w) + b: X_train에 w를 곱하고 b를 더해서 선형회귀를 계산
# tf.sigmoid(): 활성함수 sigmoid return
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
hypothesis

<tf.Tensor: id=41, shape=(455, 1), dtype=float32, numpy=
array([[2.40192771e-01],
       [1.73836827e-01],
       [2.15464830e-03],
       [3.11134934e-01],
       [7.93339729e-01],
       [5.74836075e-01],
       [3.33717436e-01],
       [8.06925893e-01],
       [8.63600373e-01],
       [6.28313005e-01],
       [8.45751882e-01],
       [8.38807166e-01],
       [7.66058505e-01],
       [8.58385324e-01],
       [6.60921574e-01],
       [4.92537826e-01],
       [7.95808434e-01],
       [8.71340334e-01],
       [2.66023070e-01],
       [3.26408148e-02],
       [8.11773002e-01],
       [6.15665197e-01],
       [7.28496790e-01],
       [1.36411846e-01],
       [1.83880925e-02],
       [7.45127857e-01],
       [6.57250881e-02],
       [8.72093678e-01],
       [7.26370573e-01],
       [1.63804889e-01],
       [2.73697913e-01],
       [8.35600615e-01],
       [5.74003696e-01],
       [4.06536251e-01],
       [5.56608975e-01],
       [6.94097340e-01],
       [6.18075252e-01],
       [8.52836668

In [27]:
# w와 b값을 자동으로 수정하는 optimizer 객체를 생성
optimizer = tf.train.AdamOptimizer(0.001)

In [30]:
# 반복해서 w와 b를 찾음
for step in range(100):
    with tf.GradientTape() as tape:
        # 로지스틱 회귀식을 변수 hypothesis에 대입
        # tf.matmul: 배열끼리 곱을 계산하는 함수
        # tf.matmul(x_data, w) + b: x_data와 w의 곱을 계산하고 b를 더함
        # hypothesis = tf.sigmoid(tf.matmul(x_data, w) + b)
        hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b)
        
        # 로지스틱 회귀식의 오차를 계산하는 계산식을 변수 cost에 대입하면
        # tensorflow에서 자동으로 오차를 가장 적게하는 w와 b의 값을 찾아줌
        # tf.log(값1): 값1의 로그값을 계산
        # tf.reduce_mean(): 평균을 계산
        cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis))
        
        # cost, w, b를 이용하여 w의 기울기, b의 기울기를 계산해서 grads에 대입
        grads = tape.gradient(cost, [w, b])
        
    # grads에 저장된 w의 기울기와 b의 기울기를 w와 b에서 뺴주고 새로운 w와 b로 업데이트
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w, b]))
    
    if step % 10 == 0:
        print("=" * 50)
        print("step: {}, cost: {}, w: {}, b: {}".format(step, cost.numpy(), w.numpy(), b.numpy()))
        print("=" * 50)

step: 0, cost: 0.3314264118671417, w: [[-0.22806492]
 [ 0.37651598]
 [-0.2563195 ]
 [-0.17685218]
 [ 0.00756585]
 [ 0.37879062]
 [-0.23736532]
 [-0.17508079]
 [-0.43086872]
 [ 0.25061113]
 [ 0.20345078]
 [-0.27676854]
 [-0.01023022]
 [-0.33297428]
 [-0.2884639 ]
 [-0.39965886]
 [-0.22834916]
 [ 0.27902722]
 [ 0.3849241 ]
 [-0.15999135]
 [-0.30910885]
 [-0.2054463 ]
 [ 0.12515889]
 [-0.28570879]
 [ 0.16370289]
 [-0.27135664]
 [ 0.2999097 ]
 [-0.3450693 ]
 [-0.35164684]
 [ 0.23860745]], b: [0.12696594]
step: 10, cost: 0.30842939019203186, w: [[-0.23801284]
 [ 0.3665502 ]
 [-0.26626542]
 [-0.1868003 ]
 [-0.00237772]
 [ 0.36887184]
 [-0.2472989 ]
 [-0.18502255]
 [-0.44074756]
 [ 0.2407965 ]
 [ 0.19350156]
 [-0.26683274]
 [-0.02017276]
 [-0.3429224 ]
 [-0.27849725]
 [-0.40890145]
 [-0.2381361 ]
 [ 0.26914102]
 [ 0.39492738]
 [-0.1498873 ]
 [-0.31906006]
 [-0.21541314]
 [ 0.1152102 ]
 [-0.29565942]
 [ 0.15374812]
 [-0.28128672]
 [ 0.2899729 ]
 [-0.35501316]
 [-0.3615949 ]
 [ 0.22867851]], b:

In [31]:
# Gradient Decent를 이용해서 계산이 완료된 w
w

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.31041628],
       [ 0.2874141 ],
       [-0.33823308],
       [-0.25939536],
       [-0.0742693 ],
       [ 0.30419683],
       [-0.31706503],
       [-0.2566397 ],
       [-0.48827904],
       [ 0.2170927 ],
       [ 0.11834554],
       [-0.21109135],
       [-0.09354571],
       [-0.41698977],
       [-0.21208571],
       [-0.32178554],
       [-0.2502122 ],
       [ 0.21052735],
       [ 0.47375244],
       [-0.05785387],
       [-0.3927095 ],
       [-0.29459742],
       [ 0.04220798],
       [-0.36920908],
       [ 0.0784874 ],
       [-0.34951985],
       [ 0.21943228],
       [-0.42711872],
       [-0.43478024],
       [ 0.1597623 ]], dtype=float32)>

In [32]:
# Gradient Decent를 이용해서 계산이 완료된 b
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.20816939], dtype=float32)>

In [33]:
# scaler를 이용해서 X_test의 범위를 변경함
# 위에서 scaler.fit(X_train) 함수를 실행했기 때문에 scaler에 X_train의 평균, 표준편차가 저장되어 있음
# scaler.transform(X_test): X_test에서 X_train의 평균을 뺴고 X_train의 표준편차로 나눠줌
X_test = scaler.transform(X_test)
X_test

array([[ 0.48485786, -0.36184686,  0.5334138 , ...,  1.0330875 ,
         2.150087  ,  2.1462686 ],
       [ 0.80301607,  1.4003353 ,  0.75159293, ...,  0.84611595,
        -0.6368927 , -0.24992242],
       [-0.7961459 , -1.1658131 , -0.7736407 , ..., -0.72025687,
        -0.90614337, -0.14612015],
       ...,
       [-0.77660996, -0.7965493 , -0.7409139 , ..., -0.10220366,
        -0.18499263, -0.5323733 ],
       [-1.3358979 , -0.60490626, -1.2992908 , ..., -0.54046494,
         0.12204781,  0.7777191 ],
       [-0.9245254 , -0.1398211 , -0.82818544, ...,  2.0202975 ,
         1.9674377 ,  3.0750248 ]], dtype=float32)

In [34]:
# X_test에 w를 곱하고 b를 추가한 후 활성함수를 이용해서 데이터의 범위를 0 ~ 1로 설정
predict = tf.sigmoid(tf.matmul(X_test, w) + b)
predict

<tf.Tensor: id=6442, shape=(114, 1), dtype=float32, numpy=
array([[7.5867206e-02],
       [1.3300958e-01],
       [8.3305705e-01],
       [9.1021937e-01],
       [9.0126759e-01],
       [9.7977585e-01],
       [6.7942250e-01],
       [8.0211520e-01],
       [8.0644268e-01],
       [9.0614212e-01],
       [5.0898671e-02],
       [9.6842599e-01],
       [8.6858940e-01],
       [9.1044176e-01],
       [5.9933364e-03],
       [7.0579559e-01],
       [7.4267977e-01],
       [8.4385431e-01],
       [6.1362982e-05],
       [6.5227449e-02],
       [8.5747284e-01],
       [9.7495586e-01],
       [5.8700061e-01],
       [6.6428304e-01],
       [8.0833215e-01],
       [6.1260426e-01],
       [3.0877966e-01],
       [9.0081513e-01],
       [9.0855747e-01],
       [8.5071146e-01],
       [9.5613647e-01],
       [6.8197399e-01],
       [8.5919297e-01],
       [1.2325922e-01],
       [9.8919129e-01],
       [7.3254704e-02],
       [7.2287005e-01],
       [8.8058746e-01],
       [8.7112582e-01],
     

In [35]:
# tf.cast(조건): 조건을 만족하는 데이터 혹은 True는 1로 변환
# 조건을 만족하지 못하는 데이터 혹은 False는 0으로 변환
# -> 0.5 초과는 1로 변환, 0.5 이하는 0으로 변환
predict01 = tf.cast(predict > 0.5, dtype = tf.float32)
print("="*50)
print("predict01")
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]], shape=(114, 1), dtype=float32)


In [36]:
# tf.equal(predict01, y_test): 조건을 만족하면 해당 줄칸에 True 또는 False return
# tf.equal(predict01, y_test): predict와 y_test의 값이 같으면 해당 줄칸에 True 또는 False return
ac01 = tf.equal(predict01, y_test)
ac01

<tf.Tensor: id=6447, shape=(114, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],


In [37]:
# tf.cast(): True는 1로 변환, False는 0으로 변환
ac02 = tf.cast(ac01, dtype = "float32")
ac02

<tf.Tensor: id=6448, shape=(114, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
     

In [38]:
# tf.reduce_mean(): 변환한 0과 1으 ㅣ합을 구한 후에 데이터의 개수로 나눔
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=6450, shape=(), dtype=float32, numpy=0.9298246>

In [39]:
# 정확도를 계산
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype = tf.float32))
print("="*50)
print("accuracy")
print(accuracy.numpy())

accuracy
0.9298246
