In [8]:
word_list=[
    "남자 남자 남자 밥을 먹는다",
    "남자 남자 걷는다",
    "남자 남자 남자",
    "남자 남자 남자 남자",
    "남자 남자 남자 여자 여자",
    "남자 남자 남자 밥 밥 먹는다"
]

In [9]:
n=6

In [10]:
import math

In [11]:
#남자 IDF
idf1=math.log((1+n)/(1+6))+1
idf1

1.0

In [12]:
#여자 IDF
idf2=math.log((1+n)/(1+1))+1
idf2

2.252762968495368

In [13]:
#밥 IDF
idf3=math.log((1+n)/(1+2))+1
idf3

1.8472978603872037

In [14]:
word_list[0]

'남자 남자 남자 밥을 먹는다'

In [15]:
#첫번째 문장 남자->숫자값 TF*IDF
tfidf11=3*idf1
tfidf11

3.0

In [17]:
#첫번째 문장 밥 숫자값 ->TF*IDF
tfidf13=1*idf3
round(tfidf13, 4)

1.8473

In [30]:
import numpy as np

In [31]:
np.array([3,0,1.8473])/np.sqrt(3*3+1.8473*1.8473)

array([0.85151308, 0.        , 0.52433337])

In [32]:
#TFIDF?
#밥->0
#남자 TFIDF?
#여자 TFIDF?
print("word_list[4]:",word_list[4])
#남자의 TFIDF
tfidf51=3*idf1
print("word_list[4] 남자 TFIDF:",tfidf51)

#여자의 TFIDF
tfidf52=2*idf2
print("word_list[4] 여자 TFIDF:",tfidf52)
#남자 여자 TFIDF normilize
print(
    np.array([3, 4.5055, 0])/math.sqrt(pow(3,2)+pow(4.5055,2))
)

word_list[4]: 남자 남자 남자 여자 여자
word_list[4] 남자 TFIDF: 3.0
word_list[4] 여자 TFIDF: 4.505525936990736
[0.55423114 0.83236281 0.        ]


In [33]:
#TFIDF?
#여자 ->TFIDF:0
#남자 TFIDF?
#밥 TDIDF ?
print("word_list[5]:",word_list[5])
#남자의 TFIDF
tfidf61=3*idf1
print("word_list[5] 남자 TFIDF:",tfidf61)

#밥의 TFIDF
tfidf63=2*idf3
print("word_list[5] 밥 TFIDF:",tfidf63)
#남자 밥 TFIDF normalize
print(
    np.array([3, 0, 3.6946])/np.sqrt(3*3+3.6946*3.6946)
)

word_list[5]: 남자 남자 남자 밥 밥 먹는다
word_list[5] 남자 TFIDF: 3.0
word_list[5] 밥 TFIDF: 3.6945957207744073
[0.63035687 0.         0.77630549]


In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
vectorlizer=TfidfVectorizer()

In [36]:
X_train_vector=vectorlizer.fit_transform(word_list)

In [37]:
X_train_vector.A

array([[0.        , 0.71739444, 0.44174707, 0.53870654, 0.        ],
       [0.747814  , 0.66390829, 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.55422893, 0.        , 0.        , 0.83236428],
       [0.        , 0.85151335, 0.52433293, 0.        , 0.        ]])

In [38]:
vectorlizer.get_feature_names()

['걷는다', '남자', '먹는다', '밥을', '여자']

In [40]:
import pandas as pd

In [41]:
pd.DataFrame(
    X_train_vector.A, 
    columns=vectorlizer.get_feature_names())

걷는다        남자       먹는다        밥을        여자
0  0.000000  0.717394  0.441747  0.538707  0.000000
1  0.747814  0.663908  0.000000  0.000000  0.000000
2  0.000000  1.000000  0.000000  0.000000  0.000000
3  0.000000  1.000000  0.000000  0.000000  0.000000
4  0.000000  0.554229  0.000000  0.000000  0.832364
5  0.000000  0.851513  0.524333  0.000000  0.000000

In [42]:
from konlpy.tag import Twitter
twitter=Twitter()

C:\ai\python\anaconda3\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')
C:\ai\python\anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


In [45]:
def getNounAndAdjective(text):
    stems=[]
    tagged=twitter.pos(text, stem=True)
    print("tagged:",tagged)
    for i in range(0, len(tagged)):
        print("i=",i,
              ":tagged[i]:",tagged[i])
        if(tagged[i][1]=="Noun"):
            stems.append(tagged[i][0])
            
    return stems

In [46]:
getNounAndAdjective(
    "아버지가 방에 들어가신다 슬프다 ")

tagged: [('아버지', 'Noun'), ('가', 'Josa'), ('방', 'Noun'), ('에', 'Josa'), ('들어가다', 'Verb'), ('슬프다', 'Adjective')]
i= 0 :tagged[i]: ('아버지', 'Noun')
i= 1 :tagged[i]: ('가', 'Josa')
i= 2 :tagged[i]: ('방', 'Noun')
i= 3 :tagged[i]: ('에', 'Josa')
i= 4 :tagged[i]: ('들어가다', 'Verb')
i= 5 :tagged[i]: ('슬프다', 'Adjective')


['아버지', '방']

In [47]:
vectorlizer=TfidfVectorizer(
    tokenizer=getNounAndAdjective)

X_train_vector=vectorlizer.fit_transform(
    word_list)

tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('밥', 'Noun'), ('을', 'Josa'), ('먹다', 'Verb')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
i= 3 :tagged[i]: ('밥', 'Noun')
i= 4 :tagged[i]: ('을', 'Josa')
i= 5 :tagged[i]: ('먹다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('걷다', 'Verb')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('걷다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
i= 3 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('여자', 'Noun'), ('여자', 'Noun')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
i= 3 :tagged[i]

In [48]:
pd.DataFrame(X_train_vector.A ,
            columns=vectorlizer.get_feature_names())

남자         밥        여자
0  0.851513  0.524333  0.000000
1  1.000000  0.000000  0.000000
2  1.000000  0.000000  0.000000
3  1.000000  0.000000  0.000000
4  0.554229  0.000000  0.832364
5  0.630357  0.776305  0.000000

In [49]:
vectorlizer=TfidfVectorizer(
    tokenizer=getNounAndAdjective, min_df=2)

X_train_vector=vectorlizer.fit_transform(word_list)

tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('밥', 'Noun'), ('을', 'Josa'), ('먹다', 'Verb')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
i= 3 :tagged[i]: ('밥', 'Noun')
i= 4 :tagged[i]: ('을', 'Josa')
i= 5 :tagged[i]: ('먹다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('걷다', 'Verb')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('걷다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
i= 3 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('여자', 'Noun'), ('여자', 'Noun')]
i= 0 :tagged[i]: ('남자', 'Noun')
i= 1 :tagged[i]: ('남자', 'Noun')
i= 2 :tagged[i]: ('남자', 'Noun')
i= 3 :tagged[i]

In [50]:
pd.DataFrame(X_train_vector.A ,
            columns=vectorlizer.get_feature_names())

남자         밥
0  0.851513  0.524333
1  1.000000  0.000000
2  1.000000  0.000000
3  1.000000  0.000000
4  1.000000  0.000000
5  0.630357  0.776305

In [51]:
youtube_dic={
      "title":["t1","t2","t3","t4","t5"],
      "view_num2":[1,2,3,4,5]     
 }
youtube=pd.DataFrame(youtube_dic)
youtube

title  view_num2
0    t1          1
1    t2          2
2    t3          3
3    t4          4
4    t5          5

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
train_test_split(
     youtube["title"],youtube["view_num2"]
)

[2    t3
 4    t5
 1    t2
 Name: title, dtype: object, 3    t4
 0    t1
 Name: title, dtype: object, 2    3
 4    5
 1    2
 Name: view_num2, dtype: int64, 3    4
 0    1
 Name: view_num2, dtype: int64]

In [54]:
X_train, X_test, y_train, y_test = train_test_split(
     youtube["title"],youtube["view_num2"]
)

In [55]:
X_train

3    t4
2    t3
0    t1
Name: title, dtype: object

In [56]:
X_test

4    t5
1    t2
Name: title, dtype: object

In [57]:
y_train

3    4
2    3
0    1
Name: view_num2, dtype: int64

In [58]:
y_test

4    5
1    2
Name: view_num2, dtype: int64