In [7]:
word_list=[
    "남자 남자 남자 밥을 먹는다",
    "남자 남자 걷는다",
    "남자 남자 남자",
    "남자 남자 남자 남자",
    "남자 남자 남자 여자 여자",
    "남자 남자 남자 밥 밥 먹는다"
]

In [8]:
n = 6 # 전체 문장의 수

In [72]:
import math
import pandas as pd

In [17]:
#남자 IDF
idf1 = math.log((1+n)/(1+6))+1
idf1

1.0

In [16]:
#여자 IDF
idf2 = math.log((1+n)/(1+1))+1
idf2

2.252762968495368

In [19]:
#밥 IDF
idf3 = math.log((1+n)/(1+2))+1
idf3

1.8472978603872037

In [20]:
word_list[0]

'남자 남자 남자 밥을 먹는다'

In [22]:
# 첫번째 문장에서 남자 // TF-IDF 구하기 숫자값 TF*IDF
# log(1) = 0
tfidf11= 3*idf1
tfidf11

3.0

In [26]:
# 첫번째 문장에서 밥 숫자값 -> TF*IDF
tfidf13 = 1*idf3
round(tfidf13,4)

1.8473

In [37]:
import numpy as np

In [38]:
np.array([3, 0, 1.8473])/np.sqrt(3*3 + 1.8473*1.8473)

array([0.85151308, 0.        , 0.52433337])

In [27]:
word_list[4]
# 남자 여자 normailize

'남자 남자 남자 여자 여자'

In [45]:
print(
    np.array([3, 4.505, 0])/np.sqrt(math.pow(3,2) + math.pow(4.505, 2))
)

[0.55427376 0.83233443 0.        ]


In [30]:
tfidf21 = 3*idf1
tfidf21

3.0

In [35]:
tfidf22 = 2*idf2
tfidf22

4.505525936990736

In [32]:
#TFIDF
#여자 TFIDF 0
#남자 TFIDF
#밥 TFIDF
word_list[5]
# 남자 밥 normailize

'남자 남자 남자 밥 밥 먹는다'

In [46]:
print(
    np.array([3, 0, 3.694])/np.sqrt(math.pow(3,2) + math.pow(3.694, 2))
)

[0.63041856 0.         0.77625539]


In [33]:
tfidf31 = 3*idf1
tfidf31

3.0

In [34]:
tfidf32 = 2*idf3
tfidf32

3.6945957207744073

Help on built-in function pow in module builtins:

pow(x, y, z=None, /)
    Equivalent to x**y (with two arguments) or x**y % z (with three arguments)
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [42]:
math.pow(3,2)

9.0

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [107]:
vectorizer = TfidfVectorizer()

In [108]:
X_train_vector = vectorizer.fit_transform(word_list)

In [64]:
# 계산된 내용 들어있는 곳
X_train_vector.A

array([[0.        , 0.71739444, 0.44174707, 0.53870654, 0.        ],
       [0.747814  , 0.66390829, 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.55422893, 0.        , 0.        , 0.83236428],
       [0.        , 0.85151335, 0.52433293, 0.        , 0.        ]])

In [109]:
vectorizer.get_feature_names()

['걷는다', '남자', '먹는다', '밥을', '여자']

In [110]:
pd.DataFrame(
    X_train_vector.A,
    columns = vectorizer.get_feature_names())

걷는다        남자       먹는다        밥을        여자
0  0.000000  0.717394  0.441747  0.538707  0.000000
1  0.747814  0.663908  0.000000  0.000000  0.000000
2  0.000000  1.000000  0.000000  0.000000  0.000000
3  0.000000  1.000000  0.000000  0.000000  0.000000
4  0.000000  0.554229  0.000000  0.000000  0.832364
5  0.000000  0.851513  0.524333  0.000000  0.000000

In [74]:
from konlpy.tag import Twitter
twitter = Twitter()

C:\ai\python\anaconda3\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')
C:\ai\python\anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


In [117]:
def getNounAndAdjective(text):
    stems = []
    tagged = twitter.pos(text, stem = True)
    print('tagged:',tagged)
    for i in range(0, len(tagged)):
        print("i = ", i, ":tagged[i]:", tagged[i])
        if(tagged[i][1] == 'Noun'):
            stems.append(tagged[i][0])
    
    return stems

In [112]:
getNounAndAdjective(
    "아버지가 방에 들어 가신다 그래서 슬프다")

tagged: [('아버지', 'Noun'), ('가', 'Josa'), ('방', 'Noun'), ('에', 'Josa'), ('들다', 'Verb'), ('가다', 'Verb'), ('그래서', 'Adverb'), ('슬프다', 'Adjective')]
i =  0 :tagged[i]: ('아버지', 'Noun')
i =  1 :tagged[i]: ('가', 'Josa')
i =  2 :tagged[i]: ('방', 'Noun')
i =  3 :tagged[i]: ('에', 'Josa')
i =  4 :tagged[i]: ('들다', 'Verb')
i =  5 :tagged[i]: ('가다', 'Verb')
i =  6 :tagged[i]: ('그래서', 'Adverb')
i =  7 :tagged[i]: ('슬프다', 'Adjective')


['아버지', '방', '슬프다']

In [118]:
vectorizer = TfidfVectorizer(
    tokenizer = getNounAndAdjective)

X_train_vector = vectorizer.fit_transform(word_list)

tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('밥', 'Noun'), ('을', 'Josa'), ('먹다', 'Verb')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('남자', 'Noun')
i =  3 :tagged[i]: ('밥', 'Noun')
i =  4 :tagged[i]: ('을', 'Josa')
i =  5 :tagged[i]: ('먹다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('걷다', 'Verb')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('걷다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('남자', 'Noun')
i =  3 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('여자', 'Noun'), ('여자', 'Noun')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tag

In [119]:
pd.DataFrame(X_train_vector.A,
            columns = vectorizer.get_feature_names())

남자         밥        여자
0  0.851513  0.524333  0.000000
1  1.000000  0.000000  0.000000
2  1.000000  0.000000  0.000000
3  1.000000  0.000000  0.000000
4  0.554229  0.000000  0.832364
5  0.630357  0.776305  0.000000

In [126]:
vectorizer = TfidfVectorizer(
    tokenizer = getNounAndAdjective, min_df = 2)

X_train_vector = vectorizer.fit_transform(word_list)

pd.DataFrame(X_train_vector.A,
            columns = vectorizer.get_feature_names())

tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('밥', 'Noun'), ('을', 'Josa'), ('먹다', 'Verb')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('남자', 'Noun')
i =  3 :tagged[i]: ('밥', 'Noun')
i =  4 :tagged[i]: ('을', 'Josa')
i =  5 :tagged[i]: ('먹다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('걷다', 'Verb')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('걷다', 'Verb')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tagged[i]: ('남자', 'Noun')
i =  3 :tagged[i]: ('남자', 'Noun')
tagged: [('남자', 'Noun'), ('남자', 'Noun'), ('남자', 'Noun'), ('여자', 'Noun'), ('여자', 'Noun')]
i =  0 :tagged[i]: ('남자', 'Noun')
i =  1 :tagged[i]: ('남자', 'Noun')
i =  2 :tag

남자         밥
0  0.851513  0.524333
1  1.000000  0.000000
2  1.000000  0.000000
3  1.000000  0.000000
4  1.000000  0.000000
5  0.630357  0.776305

In [127]:
youtube_dic = {
    "title" : ['t1','t2','t3','t4','t5'],
    "view_num2":[1,2,3,4,5]
}
youtube = pd.DataFrame(youtube_dic)
youtube

title  view_num2
0    t1          1
1    t2          2
2    t3          3
3    t4          4
4    t5          5

In [128]:
from sklearn.model_selection import train_test_split

In [129]:
train_test_split(
    youtube["title"], youtube["view_num2"]
)

[4    t5
 2    t3
 1    t2
 Name: title, dtype: object, 3    t4
 0    t1
 Name: title, dtype: object, 4    5
 2    3
 1    2
 Name: view_num2, dtype: int64, 3    4
 0    1
 Name: view_num2, dtype: int64]

In [134]:
X_train, X_test, y_train, y_test = train_test,
    youtube["title"], youtube["view_num2"]
)

IndentationError: unexpected indent (<ipython-input-134-91c54f146446>, line 2)

In [132]:
X_train

NameError: name 'X_train' is not defined

In [ ]:
X_test